name: r_conda
channels:
  - conda-forge
  - defaults
dependencies:
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - comm=0.2.3
  - curl=8.14.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc_impl_linux-64=15.1.0
  - gfortran_impl_linux-64=15.1.0
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=15.1.0
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=11.3.3
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lark=1.2.2
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.3
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsanitizer=15.1.0
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - make=4.4.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlopt=2.9.0
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - numpy=2.3.2
  - openssl=3.5.2
  - overrides=7.7.0
  - packaging=25.0
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parso=0.8.4
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.8
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.1
  - r-abind=1.4_5
  - r-arrayhelpers=1.1_0
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bayesplot=1.13.0
  - r-bayesrules=0.0.2
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-blob=1.2.4
  - r-boot=1.3_31
  - r-broom=1.0.9
  - r-broom.mixed=0.2.9.6
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-cellranger=1.1.0
  - r-checkmate=2.3.2
  - r-class=7.3_23
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-coda=0.19_4.1
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-colourpicker=1.3.0
  - r-commonmark=2.0.0
  - r-conflicted=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-crosstalk=1.2.1
  - r-curl=6.4.0
  - r-data.table=1.17.8
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-desc=1.4.3
  - r-digest=0.6.37
  - r-distributional=0.5.0
  - r-dplyr=1.1.4
  - r-dt=0.33
  - r-dtplyr=1.3.1
  - r-dygraphs=1.1.1.6
  - r-e1071=1.7_16
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.4
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-forcats=1.0.0
  - r-fs=1.6.6
  - r-furrr=0.3.1
  - r-future=1.67.0
  - r-gargle=1.5.2
  - r-gbrd=0.4.12
  - r-generics=0.1.4
  - r-ggdist=3.3.3
  - r-ggplot2=3.5.2
  - r-ggridges=0.5.6
  - r-globals=0.18.0
  - r-glue=1.8.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gridextra=2.3
  - r-groupdata2=2.0.5
  - r-gtable=0.3.6
  - r-gtools=3.9.5
  - r-haven=2.5.5
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-ids=1.0.1
  - r-igraph=2.1.4
  - r-inline=0.3.21
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-isoband=0.2.7
  - r-janitor=2.2.1
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-later=1.4.2
  - r-lattice=0.22_7
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-litedown=0.7
  - r-lme4=1.1_37
  - r-loo=2.8.0
  - r-lubridate=1.9.4
  - r-magrittr=2.0.3
  - r-markdown=2.0
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-matrixstats=1.5.0
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-minqa=1.2.8
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-nloptr=2.2.1
  - r-numbers=0.8_5
  - r-numderiv=2016.8_1.1
  - r-openssl=2.3.3
  - r-packrat=0.9.3
  - r-parallelly=1.45.1
  - r-pbdzmq=0.3_14
  - r-pillar=1.11.0
  - r-pkgbuild=1.4.8
  - r-pkgconfig=2.0.3
  - r-pki=0.1_14
  - r-plyr=1.8.9
  - r-posterior=1.6.1
  - r-prettyunits=1.2.0
  - r-processx=3.8.6
  - r-progress=1.2.3
  - r-promises=1.3.3
  - r-proxy=0.4_27
  - r-ps=1.9.1
  - r-purrr=1.1.0
  - r-quadprog=1.5_8
  - r-quickjsr=1.8.0
  - r-r6=2.6.1
  - r-ragg=1.4.0
  - r-rappdirs=0.3.3
  - r-rbibutils=2.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rcppeigen=0.3.4.0.2
  - r-rcppparallel=5.1.9
  - r-rcpptoml=0.2.3
  - r-rdpack=2.6.4
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-rearrr=0.3.5
  - r-reformulas=0.4.1
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-renv=1.1.5
  - r-repr=1.1.7
  - r-reprex=2.1.1
  - r-reshape2=1.4.4
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-rprojroot=2.1.0
  - r-rsconnect=1.5.0
  - r-rstan=2.32.7
  - r-rstanarm=2.32.1
  - r-rstantools=2.4.0
  - r-rstudioapi=0.17.1
  - r-rvest=1.0.4
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-selectr=0.4_2
  - r-shiny=1.11.1
  - r-shinyjs=2.1.0
  - r-shinystan=2.6.0
  - r-shinythemes=1.2.0
  - r-snakecase=0.11.1
  - r-snowflakeauth=0.1.2
  - r-sourcetools=0.1.7_1
  - r-stanheaders=2.32.10
  - r-stringi=1.8.7
  - r-stringr=1.5.1
  - r-survival=3.8_3
  - r-svunit=1.0.6
  - r-sys=3.4.3
  - r-systemfonts=1.2.3
  - r-tensora=0.36.2.1
  - r-textshaping=1.0.1
  - r-threejs=0.3.4
  - r-tibble=3.3.0
  - r-tidybayes=3.0.7
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-tinytex=0.57
  - r-tzdb=0.5.0
  - r-utf8=1.2.6
  - r-uuid=1.2_1
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-withr=3.0.2
  - r-xfun=0.52
  - r-xml2=1.3.8
  - r-xtable=1.8_4
  - r-xts=0.14.1
  - r-yaml=2.3.10
  - r-zoo=1.8_14
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.27.0
  - sed=4.9
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.7
  - stack_data=0.6.3
  - sysroot_linux-64=2.34
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tktable=2.10
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250708
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - widgetsnbextension=4.0.14
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
